name: tests

trigger: ["*"]
pr: ["*"]

pool:
  vmImage: "ubuntu-20.04"

jobs:
  - job: run_test
    strategy:
      matrix:
        python3_7:
          python.version: "3.7"
        python3_8:
          python.version: "3.8"

    timeoutInMinutes: 10

    steps:
      - task: UsePythonVersion@0
        displayName: Set python version
        inputs:
          versionSpec: "$(python.version)"
      - script: |
          sudo apt-get update
          sudo apt-get install -y default-libmysqlclient-dev libfuzzy-dev libfuzzy2
          sudo rm -rf /var/lib/apt/lists/*
          sudo env "PATH=$PATH" python -m pip install -U --no-cache-dir assemblyline assemblyline_v4_service
          [ -f $(pwd)/requirements.txt ] && sudo env "PATH=$PATH" python -m pip install -U --no-cache-dir -r $(pwd)/requirements.txt
          [ -f $(pwd)/tests/requirements.txt ] && sudo env "PATH=$PATH" python -m pip install -U --no-cache-dir -r $(pwd)/tests/requirements.txt
          sudo rm -rf /tmp/* /var/lib/apt/lists/* ~/.cache/pip
        displayName: Setup environment
      - script: python -m pytest --durations=10 -rsx -vv --cov-report=xml --cov=oletools_
        displayName: Test
      - script: python -m codecov
        displayName: Upload Coverage
